spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jq_shop
    username: root
    password: 3412410
    driver-class-name: com.mysql.cj.jdbc.Driver
    #指定数据库连接池的类型
    #最大等待连接中的数量，设0为没有限制
    #最大连接活动数
    #最大等待毫秒数，单位ms，超过时间会出现错误信息
    #数据库连接池初始化连接数
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      max-idle: 10
      max-total: 50
      max-wait-millis: 10000
      initial-size: 5
  mvc:
    view:
      prefix: /
      suffix: .html

mybatis:
  type-aliases-package: com.shop.heima.entity
  mapper-locations: classpath:/com/shop/heima/mapper/*.xml

